spring:
  application:
    name: library-kata

  r2dbc:
    url: r2dbc:h2:mem:///librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    root: INFO
    com.vg: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.h2: DEBUG
